# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/lib/python3.5/dist-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /usr/local/lib/python3.5/dist-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/Downloads/SuccinctEdgePrivate

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/Downloads/SuccinctEdgePrivate

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/lib/python3.5/dist-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/lib/python3.5/dist-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Downloads/SuccinctEdgePrivate/CMakeFiles /home/pi/Downloads/SuccinctEdgePrivate//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/Downloads/SuccinctEdgePrivate/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SuccinctEdge_cata

# Build rule for target.
SuccinctEdge_cata: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SuccinctEdge_cata
.PHONY : SuccinctEdge_cata

# fast build rule for target.
SuccinctEdge_cata/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/build
.PHONY : SuccinctEdge_cata/fast

BitMap.o: BitMap.cpp.o

.PHONY : BitMap.o

# target to build an object file
BitMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/BitMap.cpp.o
.PHONY : BitMap.cpp.o

BitMap.i: BitMap.cpp.i

.PHONY : BitMap.i

# target to preprocess a source file
BitMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/BitMap.cpp.i
.PHONY : BitMap.cpp.i

BitMap.s: BitMap.cpp.s

.PHONY : BitMap.s

# target to generate assembly for a file
BitMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/BitMap.cpp.s
.PHONY : BitMap.cpp.s

DataBlock.o: DataBlock.cpp.o

.PHONY : DataBlock.o

# target to build an object file
DataBlock.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/DataBlock.cpp.o
.PHONY : DataBlock.cpp.o

DataBlock.i: DataBlock.cpp.i

.PHONY : DataBlock.i

# target to preprocess a source file
DataBlock.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/DataBlock.cpp.i
.PHONY : DataBlock.cpp.i

DataBlock.s: DataBlock.cpp.s

.PHONY : DataBlock.s

# target to generate assembly for a file
DataBlock.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/DataBlock.cpp.s
.PHONY : DataBlock.cpp.s

DataSeries.o: DataSeries.cpp.o

.PHONY : DataSeries.o

# target to build an object file
DataSeries.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/DataSeries.cpp.o
.PHONY : DataSeries.cpp.o

DataSeries.i: DataSeries.cpp.i

.PHONY : DataSeries.i

# target to preprocess a source file
DataSeries.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/DataSeries.cpp.i
.PHONY : DataSeries.cpp.i

DataSeries.s: DataSeries.cpp.s

.PHONY : DataSeries.s

# target to generate assembly for a file
DataSeries.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/DataSeries.cpp.s
.PHONY : DataSeries.cpp.s

DataTypeStore.o: DataTypeStore.cpp.o

.PHONY : DataTypeStore.o

# target to build an object file
DataTypeStore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/DataTypeStore.cpp.o
.PHONY : DataTypeStore.cpp.o

DataTypeStore.i: DataTypeStore.cpp.i

.PHONY : DataTypeStore.i

# target to preprocess a source file
DataTypeStore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/DataTypeStore.cpp.i
.PHONY : DataTypeStore.cpp.i

DataTypeStore.s: DataTypeStore.cpp.s

.PHONY : DataTypeStore.s

# target to generate assembly for a file
DataTypeStore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/DataTypeStore.cpp.s
.PHONY : DataTypeStore.cpp.s

Dictionary.o: Dictionary.cpp.o

.PHONY : Dictionary.o

# target to build an object file
Dictionary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/Dictionary.cpp.o
.PHONY : Dictionary.cpp.o

Dictionary.i: Dictionary.cpp.i

.PHONY : Dictionary.i

# target to preprocess a source file
Dictionary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/Dictionary.cpp.i
.PHONY : Dictionary.cpp.i

Dictionary.s: Dictionary.cpp.s

.PHONY : Dictionary.s

# target to generate assembly for a file
Dictionary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/Dictionary.cpp.s
.PHONY : Dictionary.cpp.s

JoinLine.o: JoinLine.cpp.o

.PHONY : JoinLine.o

# target to build an object file
JoinLine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/JoinLine.cpp.o
.PHONY : JoinLine.cpp.o

JoinLine.i: JoinLine.cpp.i

.PHONY : JoinLine.i

# target to preprocess a source file
JoinLine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/JoinLine.cpp.i
.PHONY : JoinLine.cpp.i

JoinLine.s: JoinLine.cpp.s

.PHONY : JoinLine.s

# target to generate assembly for a file
JoinLine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/JoinLine.cpp.s
.PHONY : JoinLine.cpp.s

JoinTable.o: JoinTable.cpp.o

.PHONY : JoinTable.o

# target to build an object file
JoinTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/JoinTable.cpp.o
.PHONY : JoinTable.cpp.o

JoinTable.i: JoinTable.cpp.i

.PHONY : JoinTable.i

# target to preprocess a source file
JoinTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/JoinTable.cpp.i
.PHONY : JoinTable.cpp.i

JoinTable.s: JoinTable.cpp.s

.PHONY : JoinTable.s

# target to generate assembly for a file
JoinTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/JoinTable.cpp.s
.PHONY : JoinTable.cpp.s

JoinVariables.o: JoinVariables.cpp.o

.PHONY : JoinVariables.o

# target to build an object file
JoinVariables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/JoinVariables.cpp.o
.PHONY : JoinVariables.cpp.o

JoinVariables.i: JoinVariables.cpp.i

.PHONY : JoinVariables.i

# target to preprocess a source file
JoinVariables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/JoinVariables.cpp.i
.PHONY : JoinVariables.cpp.i

JoinVariables.s: JoinVariables.cpp.s

.PHONY : JoinVariables.s

# target to generate assembly for a file
JoinVariables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/JoinVariables.cpp.s
.PHONY : JoinVariables.cpp.s

LiteMatDictionary.o: LiteMatDictionary.cpp.o

.PHONY : LiteMatDictionary.o

# target to build an object file
LiteMatDictionary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/LiteMatDictionary.cpp.o
.PHONY : LiteMatDictionary.cpp.o

LiteMatDictionary.i: LiteMatDictionary.cpp.i

.PHONY : LiteMatDictionary.i

# target to preprocess a source file
LiteMatDictionary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/LiteMatDictionary.cpp.i
.PHONY : LiteMatDictionary.cpp.i

LiteMatDictionary.s: LiteMatDictionary.cpp.s

.PHONY : LiteMatDictionary.s

# target to generate assembly for a file
LiteMatDictionary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/LiteMatDictionary.cpp.s
.PHONY : LiteMatDictionary.cpp.s

PropertyLiteMatDictionary.o: PropertyLiteMatDictionary.cpp.o

.PHONY : PropertyLiteMatDictionary.o

# target to build an object file
PropertyLiteMatDictionary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/PropertyLiteMatDictionary.cpp.o
.PHONY : PropertyLiteMatDictionary.cpp.o

PropertyLiteMatDictionary.i: PropertyLiteMatDictionary.cpp.i

.PHONY : PropertyLiteMatDictionary.i

# target to preprocess a source file
PropertyLiteMatDictionary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/PropertyLiteMatDictionary.cpp.i
.PHONY : PropertyLiteMatDictionary.cpp.i

PropertyLiteMatDictionary.s: PropertyLiteMatDictionary.cpp.s

.PHONY : PropertyLiteMatDictionary.s

# target to generate assembly for a file
PropertyLiteMatDictionary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/PropertyLiteMatDictionary.cpp.s
.PHONY : PropertyLiteMatDictionary.cpp.s

QueryEngine.o: QueryEngine.cpp.o

.PHONY : QueryEngine.o

# target to build an object file
QueryEngine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/QueryEngine.cpp.o
.PHONY : QueryEngine.cpp.o

QueryEngine.i: QueryEngine.cpp.i

.PHONY : QueryEngine.i

# target to preprocess a source file
QueryEngine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/QueryEngine.cpp.i
.PHONY : QueryEngine.cpp.i

QueryEngine.s: QueryEngine.cpp.s

.PHONY : QueryEngine.s

# target to generate assembly for a file
QueryEngine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/QueryEngine.cpp.s
.PHONY : QueryEngine.cpp.s

RDFStorage.o: RDFStorage.cpp.o

.PHONY : RDFStorage.o

# target to build an object file
RDFStorage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/RDFStorage.cpp.o
.PHONY : RDFStorage.cpp.o

RDFStorage.i: RDFStorage.cpp.i

.PHONY : RDFStorage.i

# target to preprocess a source file
RDFStorage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/RDFStorage.cpp.i
.PHONY : RDFStorage.cpp.i

RDFStorage.s: RDFStorage.cpp.s

.PHONY : RDFStorage.s

# target to generate assembly for a file
RDFStorage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/RDFStorage.cpp.s
.PHONY : RDFStorage.cpp.s

RDFTypeStore.o: RDFTypeStore.cpp.o

.PHONY : RDFTypeStore.o

# target to build an object file
RDFTypeStore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/RDFTypeStore.cpp.o
.PHONY : RDFTypeStore.cpp.o

RDFTypeStore.i: RDFTypeStore.cpp.i

.PHONY : RDFTypeStore.i

# target to preprocess a source file
RDFTypeStore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/RDFTypeStore.cpp.i
.PHONY : RDFTypeStore.cpp.i

RDFTypeStore.s: RDFTypeStore.cpp.s

.PHONY : RDFTypeStore.s

# target to generate assembly for a file
RDFTypeStore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/RDFTypeStore.cpp.s
.PHONY : RDFTypeStore.cpp.s

RankBaseElement.o: RankBaseElement.cpp.o

.PHONY : RankBaseElement.o

# target to build an object file
RankBaseElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/RankBaseElement.cpp.o
.PHONY : RankBaseElement.cpp.o

RankBaseElement.i: RankBaseElement.cpp.i

.PHONY : RankBaseElement.i

# target to preprocess a source file
RankBaseElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/RankBaseElement.cpp.i
.PHONY : RankBaseElement.cpp.i

RankBaseElement.s: RankBaseElement.cpp.s

.PHONY : RankBaseElement.s

# target to generate assembly for a file
RankBaseElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/RankBaseElement.cpp.s
.PHONY : RankBaseElement.cpp.s

StrDataRankBaseElement.o: StrDataRankBaseElement.cpp.o

.PHONY : StrDataRankBaseElement.o

# target to build an object file
StrDataRankBaseElement.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/StrDataRankBaseElement.cpp.o
.PHONY : StrDataRankBaseElement.cpp.o

StrDataRankBaseElement.i: StrDataRankBaseElement.cpp.i

.PHONY : StrDataRankBaseElement.i

# target to preprocess a source file
StrDataRankBaseElement.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/StrDataRankBaseElement.cpp.i
.PHONY : StrDataRankBaseElement.cpp.i

StrDataRankBaseElement.s: StrDataRankBaseElement.cpp.s

.PHONY : StrDataRankBaseElement.s

# target to generate assembly for a file
StrDataRankBaseElement.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/StrDataRankBaseElement.cpp.s
.PHONY : StrDataRankBaseElement.cpp.s

TCPReceiver.o: TCPReceiver.cpp.o

.PHONY : TCPReceiver.o

# target to build an object file
TCPReceiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/TCPReceiver.cpp.o
.PHONY : TCPReceiver.cpp.o

TCPReceiver.i: TCPReceiver.cpp.i

.PHONY : TCPReceiver.i

# target to preprocess a source file
TCPReceiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/TCPReceiver.cpp.i
.PHONY : TCPReceiver.cpp.i

TCPReceiver.s: TCPReceiver.cpp.s

.PHONY : TCPReceiver.s

# target to generate assembly for a file
TCPReceiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/TCPReceiver.cpp.s
.PHONY : TCPReceiver.cpp.s

TriplePattern.o: TriplePattern.cpp.o

.PHONY : TriplePattern.o

# target to build an object file
TriplePattern.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/TriplePattern.cpp.o
.PHONY : TriplePattern.cpp.o

TriplePattern.i: TriplePattern.cpp.i

.PHONY : TriplePattern.i

# target to preprocess a source file
TriplePattern.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/TriplePattern.cpp.i
.PHONY : TriplePattern.cpp.i

TriplePattern.s: TriplePattern.cpp.s

.PHONY : TriplePattern.s

# target to generate assembly for a file
TriplePattern.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/TriplePattern.cpp.s
.PHONY : TriplePattern.cpp.s

TripleStore.o: TripleStore.cpp.o

.PHONY : TripleStore.o

# target to build an object file
TripleStore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/TripleStore.cpp.o
.PHONY : TripleStore.cpp.o

TripleStore.i: TripleStore.cpp.i

.PHONY : TripleStore.i

# target to preprocess a source file
TripleStore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/TripleStore.cpp.i
.PHONY : TripleStore.cpp.i

TripleStore.s: TripleStore.cpp.s

.PHONY : TripleStore.s

# target to generate assembly for a file
TripleStore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/TripleStore.cpp.s
.PHONY : TripleStore.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SuccinctEdge_cata.dir/build.make CMakeFiles/SuccinctEdge_cata.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SuccinctEdge_cata"
	@echo "... BitMap.o"
	@echo "... BitMap.i"
	@echo "... BitMap.s"
	@echo "... DataBlock.o"
	@echo "... DataBlock.i"
	@echo "... DataBlock.s"
	@echo "... DataSeries.o"
	@echo "... DataSeries.i"
	@echo "... DataSeries.s"
	@echo "... DataTypeStore.o"
	@echo "... DataTypeStore.i"
	@echo "... DataTypeStore.s"
	@echo "... Dictionary.o"
	@echo "... Dictionary.i"
	@echo "... Dictionary.s"
	@echo "... JoinLine.o"
	@echo "... JoinLine.i"
	@echo "... JoinLine.s"
	@echo "... JoinTable.o"
	@echo "... JoinTable.i"
	@echo "... JoinTable.s"
	@echo "... JoinVariables.o"
	@echo "... JoinVariables.i"
	@echo "... JoinVariables.s"
	@echo "... LiteMatDictionary.o"
	@echo "... LiteMatDictionary.i"
	@echo "... LiteMatDictionary.s"
	@echo "... PropertyLiteMatDictionary.o"
	@echo "... PropertyLiteMatDictionary.i"
	@echo "... PropertyLiteMatDictionary.s"
	@echo "... QueryEngine.o"
	@echo "... QueryEngine.i"
	@echo "... QueryEngine.s"
	@echo "... RDFStorage.o"
	@echo "... RDFStorage.i"
	@echo "... RDFStorage.s"
	@echo "... RDFTypeStore.o"
	@echo "... RDFTypeStore.i"
	@echo "... RDFTypeStore.s"
	@echo "... RankBaseElement.o"
	@echo "... RankBaseElement.i"
	@echo "... RankBaseElement.s"
	@echo "... StrDataRankBaseElement.o"
	@echo "... StrDataRankBaseElement.i"
	@echo "... StrDataRankBaseElement.s"
	@echo "... TCPReceiver.o"
	@echo "... TCPReceiver.i"
	@echo "... TCPReceiver.s"
	@echo "... TriplePattern.o"
	@echo "... TriplePattern.i"
	@echo "... TriplePattern.s"
	@echo "... TripleStore.o"
	@echo "... TripleStore.i"
	@echo "... TripleStore.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

